# -*- coding: utf-8 -*-
"""notebookecc58b6c49

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/notebookecc58b6c49-9ae017ea-9cfe-42ab-8ec1-5a2dd7cedfd7.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20240617/auto/storage/goog4_request%26X-Goog-Date%3D20240617T091853Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D7dd2081a890d777cdedb7e95787fd1276ac3bd5baf9b50524a16bf3ac326230e38ef71c6d383ded7f384acb53d4066bbe192b406b580db88d9cdfb2e2dd73a0c151d69e419f40ab1ac91a6e160806f5a02f8bf5a31194b04bee9ddaf64beedf0cbcf6db4d44fb84d41132a701a5f8b011fd838f9ef958654611727611c00179133e58d2886eef59cc555db791e1ae5c0a2ca3c9a12332818855150e90abaeab9f6f20bc96d88e8bd3a3ef7516b3a80ce7cbc39f3ebc68538b3097e0b14de832ed68b523051556b9d40ff56ba354126050a693e5020ecdb27ce4e44c4207907bb4447cbbe5f896bac6464f21cdb095b15711f3c4afedc9c0c399ae5dc81794178
"""

import PyPDF2
import os
from openai import OpenAI
import json
import pandas as pd

from dotenv import load_dotenv
import os

# Load environment variables from the .env file
load_dotenv()

# Get the API key from the environment variables

keys =['Name','Email','Phone Number','Highest Education Degree','Highest Education Institute','CGPA','Passing Year','Useful Links','Skills','Self-Projects','Internships/Job Experience','Overall Summary']

template = f"""
You are an expert in parsing curriculum vitaes and resumes.
For the given resume, extract the following details of the candidate.
Name, Phone Number, Email, Highest Education with institute name, CGPA, Passing Year which you should leave blank if not mentioned, Useful Links,
list of self-projects and Internships/Job Experience with complete title, duration of the project and the skills used in the project
and a brief summary of the project and also give an overall summary of the resume. List the projects in reverse chronological order.
Extract overall skills and total number of years of experience
and average time spent in each company.
Generate a summary of the candidate in 3-4 lines.
Output the result in json format with keys in format of {keys} and in case of each self-projects and professional work experience consider keys as Title, Duration,Skills & Summary.
Extract from the following text:
"""

def parse_resume_content(content):
    text_from_pdf = extract_text(content)
    if text_from_pdf=="":
        print("Can't parse the provided resume")
        return None
    prompt = "{}\n{}".format(template, text_from_pdf)

    res = get_completion(prompt=prompt)
    json_obj = json.loads(res)
    return json_obj

def extract_text(content):
    pdf_data = content
    reader = PyPDF2.PdfReader(pdf_data)
    num_pages = len(reader.pages)
    text = ""

    for page in range(num_pages):
        current_page = reader.pages[page]
        text += current_page.extract_text()
    return text

client = OpenAI(
    api_key="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"
)

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]
    response = client.chat.completions.create(
            model=model,
            messages=messages,
            temperature=0,
            timeout=30,
        )
    return response.choices[0].message.content


def main(files):
    df = []
    for file in files:
        content = parse_resume_content(file)
        if content:
            row = []
            for j in keys:
                row.append(content[j])
            df.append(row)
    df = pd.DataFrame(df, columns=keys)
    df.to_csv('parsed_data.csv')   
         



